import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "animate.css/animate.min.css";
// import "react-image-gallery/styles/css/image-gallery.css";
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";
// import SpinnerLyout from "@/components/spinner/SpinnerLyout";
import { Toaster } from "react-hot-toast";
import { Providers } from "./Providers";
import { HeroUIProvider } from "@heroui/system";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper/css/swiper.min.css"
        />
        <link
          rel="stylesheet"
          href="https://unpkg.com/swiper/css/pagination.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
        />
      </Head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <HeroUIProvider>
          <Providers>
            <Toaster position="top-center" />
            {children}
          </Providers>
        </HeroUIProvider>
      </body>
    </html>
  );
}
